services:
  app:
    build:
      context: .
      args:
        VITE_CESIUM_ION_TOKEN: ${VITE_CESIUM_ION_TOKEN}
        VITE_TILESERVER_URL: ${VITE_TILESERVER_URL}
        VITE_NOMINATIM_BASE_URL: ${VITE_NOMINATIM_BASE_URL}
    ports:
      - "3000:80"
    depends_on:
      - tileserver
      - nominatim

  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: tileserver-gl
    ports:
      - "8085:8080"
    volumes:
      - ${TILESERVER_DATA_PATH}:/data
    environment:
      - TILESERVER_GL_CACHE=0
    user: "0:0"

  nominatim:
    image: mediagis/nominatim:5.1
    container_name: nominatim_cesium
    ports:
      - "8086:8080"
    environment:
      - PBF_PATH=/nominatim/data/${NOMINATIM_PBF_FILE}
      - NOMINATIM_PASSWORD=${NOMINATIM_PASSWORD}
      - NOMINATIM_IMPORT_STYLE=full
      - NOMINATIM_TOKENIZER=icu
      - POSTGRES_SHARED_BUFFERS=1GB
      - POSTGRES_MAINTENANCE_WORK_MEM=2GB
      - POSTGRES_AUTOVACUUM_WORK_MEM=512MB
      - POSTGRES_WORK_MEM=16MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=4GB
      - POSTGRES_SYNCHRONOUS_COMMIT=off
      - POSTGRES_CHECKPOINT_SEGMENTS=32
      - POSTGRES_CHECKPOINT_COMPLETION_TARGET=0.9
      - POSTGRES_WAL_BUFFERS=8MB
      - POSTGRES_DEFAULT_STATISTICS_TARGET=100
    volumes:
      - ${NOMINATIM_DATA_PATH}:/nominatim/data
      - nominatim-db:/var/lib/postgresql/16/main
      - nominatim-flatnode:/nominatim/flatnode
    shm_size: 1g
    restart: unless-stopped

volumes:
  nominatim-db:
    name: nominatim-db
    external: true
  nominatim-flatnode:
    name: nominatim-flatnode
    external: true
